version: '3.1'

services:
  signoz:
    image: "signoz/signoz:latest"
    ports:
      - "3301:3301"
      - "4280:4280"
      - "4317:4317"
    environment:
      - SIGNOZ_IS_DOCKER=true

    # Additional configuration can go here

